#!/bin/tcsh
# a replacement of exclusive_lock.sh
unalias rm

set file = "$1" 
set filenum = "$file"".num" 
set filerun = "$file"".run" 
while ( 1 == 1 ) 
  if ( -e line.out ) then
    @ dt = `stat -c %Y line.out` - `date +%s`
    if ( "$dt" < -59 ) then
      rm line.out
    endif
  endif
  if ( -e line.out ) then
    sleep 1s
  else
    set success = "`touch line.out`"
    if ( "$success" != "" ) continue
    break
  endif
end

set n = 1
if (-e $filenum ) then
  set n = "`cat $filenum`"
  @ n = "$n" + 1
endif
echo $n >$filenum
set nn = "`wc -l <$file`"
if ( "$n" <= "$nn" ) then
  set rec = "`head -$n $file | tail -1`"
  echo $rec >>$filerun
  echo $rec
else
  echo "alljobdone"
endif

rm line.out
