#!/bin/csh
#

set OFILE = "OSZICAR"
set CFILE = "CONTCAR"
set www = `pwd`

unalias rm
unalias cp
unalias mv
set s = "`pwd`"
set h = $s:t
set nnode = 32
set mem = 60000
set neb = 1
set ppn = 32
set knl = ""
set walltime = "24:00"
if ( "$NERSC_HOST" == "edison" ) then
  set nnode = 24
  set ppn = 24
  set walltime = "36:00"
endif

set add = '&'
set pbsop = ""
set njob = 16
set nvol = 4
set kpar = ""
set prec = ""
set incar = ""
set scale = ""
set rerun = ""
set imix = ""
set gamma = ""
foreach option ( $* )
  if (x$1 == "x-node") then
    shift
    set nnode="$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-kpar") then
    shift
    set kpar = "-kpar $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-prec") then
    shift
    set prec = "-prec $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-INCAR") then
    shift
    set incar = "-INCAR $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-Gamma") then
    set gamma = "-Gamma $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-dir") then
    shift
    set phases = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-mem") then
    shift
    set mem = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-njob") then
    shift
    set njob = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nvol") then
    shift
    set nvol = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-W") then
    shift
    set walltime = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-scale") then
    shift
    set scale = "-ethr $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-ppn") then
    shift
    set ppn = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-knl") then
    set knl = "-knl"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-IMIX") then
    shift
    set imix = "-IMIX $www/$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-rerun") then
    set rerun = "-rerun"
    if ( "$#argv" != 0 ) shift
    continue
  else
    set pbsop = "$pbsop $1"
    if ( "$#argv" != 0 ) shift
  endif
end

set file = "$s/jobfile"
echo -n >$file

foreach dir ( $phases )
#foreach dir ( V*/PBEsol/ )
#foreach dir ( tI6*/PBEsol/ )
  if ( ! -e $dir/tplate ) continue

  cd $dir
   pwd
    set nl = 0
    if ( -e frun22.dat ) set nl = `wc -l frun22.dat | awk '{print $1}'`

    if ( "$nl" > 1 ) then
      set x = `sort -k2,2g  frun22.dat | head -1 | awk '{print $3}'`
      set l0 = `ari -n -f %6.3f  -0.02 x 2 + $x`
      set l1 = `ari -n -f %6.3f   0.02 x 4 + $x`
      set lc = 0.020
      set nx = `ari -n -f %8.0f $l1 - $l0 / $lc`
      set nb = 0
      set llist = ""
      set flist = ""
      while ( "$nb" <= "$nx" )
        set lx = `ari -n -f %9.3f $lc x $nb + $l0`
        set flist = "$flist $lx"
        set of = "V$lx/OSZICAR"
        if ( ! -e $of ) then
          if ( "$nb" == 0 ) then
            set llist = "$lx"
          else
            set llist = "$llist $lx"
          endif
        else if ( -z $of ) then
          if ( "$nb" == 0 ) then
            set llist = "$lx"
          else
            set llist = "$llist $lx"
          endif
        endif
        @ nb = "$nb" + 1
      end
    else if ( -e crun ) then
      set flist = `grep "foreach ee" crun | sed "s/foreach ee (//g;s/)//g"`
      set llist = "$flist"
    endif

      set xRUN = "foreach ee ( $flist )"
      sed "s/ARUN/$xRUN/g" <~/bin/hbin/vasparun >frun

      if ( "$llist" != "" ) then
        #echo $dir $llist
        set ARUN = "foreach ee ( $llist )"
        sed "s/ARUN/$ARUN/g" <~/bin/hbin/vaspmcmdf >mcmdf
        chmod u+x mcmdf
	mcmdf -Relax
      endif
      chmod u+x frun
      frun $pbsop $gamma $incar $imix $kpar $prec $scale $rerun -node $nnode -ppn $ppn -mem $mem "$knl" >>$file
  cd $www
end
