#!/bin/bash
# exclusive_lock.sh
PRJ=""
if [ $?WORKPRJ ]; then
  PRJ=$WORKPRJ
fi
lockfile=$SCRATCH/`pwd | sed "s|$HOME/||g;s|$WORK/|$PRJ|g;s|/|_|g"`
jobfile="$1" 
jobNo="$1"".num" 
jobToRun="$1"".run" 
nn=`wc -l <$jobfile`
exec 200>$lockfile
flock -x 200

   if [ -f $jobNo ] ; then
     n=`tail -1 $jobNo | awk '{print $1}'`
   else
     n=0
   fi
   if [ $n -lt $nn ]; then
     ((n=n+1))
     echo $n `hostname`>>$jobNo
     #rec=`head -$n $jobfile | tail -1`
     rec=`sed -n "$n p" $jobfile`
     echo $rec `date`>>$jobToRun
     echo $rec `date`
   else
     echo "alljobdone"
   fi
   sleep 1s
