#!/bin/csh -f
#
set s = "`pwd`"
set h = $s:t

set dollar1 = '$1'
set add = '>&'
set q = '"'
set pbsop = ""
set Ochk = ""
set clean = "clean"
set save = "full"
foreach o ( $* )
  if ( "$o" == "-ochk" ) then
    set Ochk = "check"
  else if ( "$o" == "-brief" ) then
    set save = "brief"
  else if ( "$o" == "-noclean" ) then
    set clean = "noclean"
  else
    set pbsop = "$pbsop $o"
  endif
end

foreach ee ( 0.955 0.970 0.985 1.000 1.015 1.030 1.045 )

    set d = V"$ee"

        set run = 0
        if ( -e $d ) then
        if ( "$Ochk" == "check" && -e $d/OSZICAR ) then
          set run = `grep -v '^$' $d/OSZICAR | tail -1 | grep E0 | wc -l | awk '{print $1}'`
        endif
        if ( "$Ochk" != "check" || $run == 0 ) then
        cd $d

vasppbs $pbsop >B-"$h"
set WORKDIR = "`pwd`"
set RUNDIR = '$tmpdir'
set VSPCMD = '$VSPCMD'

cat <<end.end >>B-"$h"
if ( !(-e $RUNDIR) ) then
  mkdir $RUNDIR
else
  \rm -r $RUNDIR
  mkdir $RUNDIR
endif
cd $WORKDIR
unalias cp
unalias mv
cp -f ../tplate/KPOINTS  $RUNDIR
cp -f ../tplate/INCAR    $RUNDIR

#cp -f POTCAR   $RUNDIR

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR   $RUNDIR
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$RUNDIR/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$RUNDIR/POTCAR
endif


cp -f POSCAR   $RUNDIR

cd $RUNDIR

$VSPCMD $add $RUNDIR/B-"$h".error

if ( ! -z CONTCAR ) then
	cp -f CONTCAR $WORKDIR/.
	cp -f OSZICAR $WORKDIR/.
	cp -f OUTCAR $WORKDIR/.
	cp -f vasp*.xml $WORKDIR/.
endif

cd $WORKDIR
if ( -e OUTCAR ) gzip OUTCAR
end.end

        sbatch B-"$h"
        cd ..
        endif
        endif
end

