#!/bin/tcsh
#
set ecldatabase = "~/bin/hbin/eclIN718.dat"
set s = "`pwd`"
set h = $s:t
set pbsop = "-W 02:59 -node 1 -Q shared"
set nq = ""
set debcut = "-DebCut 0.3"
set thr2 = "-thr2 0.001"
foreach option ( $* )
  if ( "x$1" == "x-W" ) then
    shift;set pbsop = "$pbsop -W $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if ( "$1" == "-DebCut" ) then
    shift; set debcut = "-DebCut $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if ( "$1" == "-nq" ) then
    set nq = "-nq"
    shift; set nq = "$nq $1"
    shift; set nq = "$nq $1"
    shift; set nq = "$nq $1"
    if ( "$#argv" != 0 ) shift
    continue
  else
    set pbsop = "$pbsop $1"
    if ( "$#argv" != 0 ) shift
    continue
  endif
end

set www = `pwd`
set ecl = `grep $www $ecldatabase`
if ( "$ecl" != "" ) then
  if ( $?debug ) echo "******  $www skiped for repeated structure"
  #echo "******  $www skiped for repeated structure"
  exit
endif

set bjob = `pwd`/B-"$h"
vasppbs $pbsop >$bjob

set i = 0
foreach d ( V* )

    if ( -e ../$d/vdos.out ) then
      if ( ! -z ../$d/vdos.out ) then
#        set nan = `grep nan ../$d/vdos.out | wc -l`
#          if ( "$nan" == 0 ) then
            set t0 = `stat -c %Y ../$d/vdos.out`
            set t1 = `stat -c %Y $d/OSZICAR`
            @ dif =  "$t1" - "$t0"
            if ( "$dif" <= -1 ) continue
#          endif
      endif
    endif

    set num = -1
    if ( -e $d/OUTCAR.gz ) then
      set num = `zgrep THz $d/OUTCAR.gz | wc -l`
    else if ( -e $d/OUTCAR ) then
      set num = `grep THz $d/OUTCAR | wc -l`
    endif

    if ( "$num" <= -1 ) continue
    if ( "$num" == "0" ) then
	echo -n "`pwd` :"
	echo " $d not converged phonon calculations"
	continue
    else
	echo -n "`pwd` :"
	echo " $d"
    endif 
    @ i = "$i" + 1

	cd $d
set WORKDIR = "`pwd`"
echo "cd $WORKDIR" >>$bjob
vasp_fij
if ( "$status" == "0" ) then
#echo "vasp_fij" >>$bjob
echo "Yphon <superfij.out $nq $debcut -silent -tranI 2 $thr2" >>$bjob
echo "rm superfij.out" >>$bjob
echo "cp vdos.out ../../$d/." >>$bjob
echo "" >>$bjob
else
  if ( -e $d/OUTCAR ) then
    #rm OUTCAR
  else if ( -e $d/OUTCAR.gz ) then
    #rm OUTCAR.gz
  endif
  @ i = "$i" - 1
  echo "RUNNING time error for `pwd`"
endif
        cd ..
end

echo "cd $www" >>$bjob
echo "touch touched" >>$bjob

if ( "$i" != 0 ) sbatch $bjob
