#!/bin/tcsh
#
set PY = "~/prj/EV/bin/"
set s = "`pwd`"
set h = $s:t
unalias cp
unalias rm
unalias mv

set dollar1 = '$1'
set add = '>&'
set q = '"'
set qr = '`'
set pbsop = ""
set rerun = ""
set bigjob = ""
set nesting = ""
set nestfile = ""
set nesttime = ""
foreach o ( $* )
  if (x$1 == "x-kpar") then
    shift
    set KPAR = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-MAG2") then
    set MAG2
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-NBANDS") then
    shift
    set NBANDS = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nesttime") then
    shift
    set nesttime = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-AAAA") then
    shift
    set AAAA = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-rerun") then
    set rerun = "-rerun"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nesting") then
    set nesting = "-nesting"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nestfile") then
    shift
    set nestfile = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-bigjob") then
    set bigjob = "-bigjob"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-LAUTO" ) then
    set LAUTO
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-SYMPREC" ) then
    set SYMPREC
    if ( "$#argv" != 0 ) shift
    continue
  else
    set pbsop = "$pbsop $1"
    if ( "$#argv" != 0 ) shift
  endif
end  

if ( $?NBANDS ) then
  set poscar = `ls V*/POSCAR | tail -4 | head -1`
  set nat = `head -7 $poscar | tail -1`
  set nel = `zcat tplate/POTCAR.gz | grep "\.000000000000000" | grep -v E`
  set ii = 0
  set Var = 0.0
  foreach na ( $nat )
    set jj = 0
    foreach ne ( $nel )
      if ( "$ii" == "$jj" ) then
        set Var = `ari -n $na x $ne + $Var`
	break
      endif
      @ jj = "$jj" + 1
    end
    @ ii = "$ii" + 1
  end
  set Var = `ari -n -f %.0f $Var x $NBANDS`
  grep -v NBANDS tplate/INCAR > INCAR_$NERSC_HOST
  echo "NBANDS= $Var" >>INCAR_$NERSC_HOST
else if ( -e INCAR_$NERSC_HOST ) then
  rm INCAR_$NERSC_HOST
endif

if ( $?KPAR ) then
  if ( -e INCAR_$NERSC_HOST ) then
    grep -v KPAR INCAR_$NERSC_HOST >INCAR.tmp
    mv INCAR.tmp INCAR_$NERSC_HOST
    echo "KPAR= $KPAR" >>INCAR_$NERSC_HOST
  else
    grep -v KPAR tplate/INCAR >INCAR_$NERSC_HOST
    echo "KPAR= $KPAR" >>INCAR_$NERSC_HOST
  endif
endif

if ( $?LAUTO ) then
  if ( ! -e INCAR_$NERSC_HOST ) then
    cp tplate/INCAR INCAR_$NERSC_HOST
  endif
cat <<end_end >>INCAR_$NERSC_HOST
LREAL= Auto
 LPLANE = .TRUE.
 LSCALU = .FALSE.
 NSIM   = 4
end_end
endif

if ( $?SYMPREC ) then
  if ( ! -e INCAR_$NERSC_HOST ) then
    cp tplate/INCAR INCAR_$NERSC_HOST
  endif
  echo "SYMPREC= 1.e-12" >>INCAR_$NERSC_HOST
endif

foreach ee ( 0.940 0.960 0.980 1.000 1.020 1.040 1.060 1.080 1.100 )

    set d = V"$ee"

    if ( -e $d/Bigjob ) then
      if ( "$bigjob" == "" || "$rerun" == "" ) continue
    endif

        cd $d

if ( -e ../INCAR_$NERSC_HOST ) then
  cp ../INCAR_$NERSC_HOST .
else
  cp ../tplate/INCAR INCAR_$NERSC_HOST
endif

if ( $?MAG2 ) then
  set nm = `grep MAGMOM $INCAR | wc -l`
  if ( "$nm" != 0 ) then
    grep -v MAGMOM ../tplate/INCAR >INCAR_$NERSC_HOST
    set nmn = `head -7 POSCAR | tail -2 | python $PY/mag.py -MAG2`
    echo "$nmn" >>INCAR_$NERSC_HOST
  endif
endif

set AAA = "A"
if ( $?AAAA ) then
  set AAA = "$AAAA"
else
  if ( "$NERSC_HOST" == "edison" ) then
    set AAA = "E"
  endif
  if ( "$NERSC_HOST" == "cori" ) then
    set AAA = "C"
  endif
endif

vasppbsN $pbsop | grep -v tmpdir >"$AAA"-"$h"
set WORKDIR = "`pwd`"
set RUNDIR = `qqcd`

cat <<end_end >>"$AAA"-"$h"


cd $WORKDIR

if ( "$nesting" != "" ) then
  set nested = \`vaspnest $nesttime\`
  if ( "\$nested" == 0 ) then
    if ( -e Bigjob ) then
      set now = \`date +%s\`
      set bigjob = \`stat -c %Y Bigjob\`
      @ bigjob = "\$now" - "\$bigjob"
      if ( "\$bigjob" < 600 ) then
        if ( "$bigjob" == "" || "$rerun" == "" ) goto vaspnesting
      else
        goto vaspnesting
      endif
    else
      goto vaspnesting
    endif
  endif
endif

if ( -e LOCKED ) then
    @ dt = \`stat -c %Y LOCKED\` - \`date +%s\`
    if ( "\$dt" < -172800 ) then
      touch LOCKED
      set lockedbyme
    else
      goto vaspnesting
    endif
else
      touch LOCKED
      set lockedbyme
endif

if ( -e OUTCAR ) gzip -f OUTCAR

if ( -e OUTCAR.gz ) then
  set com = \`vaspprunconvergence\`
  if ( "\$com" == "0" ) then
    goto vaspnesting
  else if ( "\$com" == "1" ) then
    if ( "$rerun" == "" ) goto vaspnesting
  endif
endif

if ( !(-e $RUNDIR) ) then
  mkdir $RUNDIR
endif

set Conrec = ""
if ( -e Convergence ) then
  set econver = \`grep "convergent electronic step" Convergence | tail -1\`
  if ( "\$econver" == "not convergent electronic step" ) then
    set ptry = \`grep IMIX.0 Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.0"
      grep -v ISMEAR INCAR_$NERSC_HOST | grep -v SIGMA >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.0 >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.48 Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.48"
      grep -v IALGO INCAR_$NERSC_HOST >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.48 >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.AMIX Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.AMIX"
      grep -v MIX INCAR_$NERSC_HOST | grep -v NELM | grep -v IALGO >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.AMIX >>INCAR_$NERSC_HOST
      echo "NELM = 200" >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.MAG Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.MAG"
      set AFM = \`grep  MAGMOM INCAR_$NERSC_HOST | grep '-' | wc -l\`
      if ( "\$AFM" == "" ) then
        grep -v MAGMOM INCAR_$NERSC_HOST >INCAR.tmp
        mv INCAR.tmp INCAR_$NERSC_HOST
        goto endINCAR
      endif
    endif

    set ptry = \`grep IMIX.NORREAL Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.NONREAL"
      grep -v MIX INCAR_$NERSC_HOST | grep -v NELM | grep -v IALGO | grep -v LREAL | grep -v LPLANE | grep -v LSCALU | grep -v NSIM >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.0NOREAL Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.0NOREAL"
      grep -v ISMEAR INCAR_$NERSC_HOST | grep -v SIGMA >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.0 >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.48NOREAL Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.48NOREAL"
      grep -v IALGO INCAR_$NERSC_HOST >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.48 >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.AMIX Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.AMIXNOREAL"
      grep -v MIX INCAR_$NERSC_HOST | grep -v NELM | grep -v IALGO >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.AMIXNOREAL >>INCAR_$NERSC_HOST
      echo "NELM = 200" >>INCAR_$NERSC_HOST
      goto endINCAR
    endif

    set ptry = \`grep IMIX.MAGNOREAL Convergence | tail -1\`
    if ( "\$ptry" == "" ) then
      set Conrec = "IMIX.MAGNOREAL"
      set AFM = \`grep  MAGMOM INCAR_$NERSC_HOST | grep '-' | wc -l\`
      if ( "\$AFM" == "" ) then
        grep -v MAGMOM INCAR_$NERSC_HOST >INCAR.tmp
        mv INCAR.tmp INCAR_$NERSC_HOST
        goto endINCAR
      endif
    endif

  endif
else if ( -e Bigjob ) then
      echo "IMIX.48" >>Convergence
      grep -v IALGO INCAR_$NERSC_HOST | >INCAR.tmp
      mv INCAR.tmp INCAR_$NERSC_HOST
      cat ~/bin/hbin/IMIX.48 >>INCAR_$NERSC_HOST
endif

endINCAR:

echo "\$Conrec" >>Convergence

#set ferror = "\`ls -lt $RUNDIR/*.error |& head -1 | awk '{print $9}'\`"
set ferror = "\`ls $RUNDIR/*.error |& head -1\`"

if ( -e "\$ferror" ) then
  set b = \`grep "DUE TO TIME LIMIT" \$ferror | wc -l\`
  if ( "\$b" == 0 ) then
    set k1 = \`grep "got SIGCONT" \$ferror | wc -l\`
    set k2 = \`grep "CANCELLED AT" \$ferror | grep STEP | wc -l\`
    @ b = "\$k1" * "\$k2"
  endif
  if ( "\$b" != 0 ) then
    echo "bigjob" >Bigjob
    echo "******** Bigjob  \`pwd\` requrie long CPU" >>& /dev/stderr
  endif

  set error = \`grep "VERY BAD NEWS" \$ferror | wc -l\`
  if ( "\$error" != 0 ) then
    echo "SYMPREC = 1.e-12" >>INCAR_$NERSC_HOST
  else
    set error = \`grep "SYMPREC" \$ferror | wc -l\`
    if ( "\$error" != 0 ) then
      echo "SYMPREC = 1.e-12" >>INCAR_$NERSC_HOST
    endif
  endif
endif

cp -f ../tplate/KPOINTS  $RUNDIR
if ( -e INCAR_$NERSC_HOST ) then
  cp -f INCAR_$NERSC_HOST    $RUNDIR/INCAR
else
  cp -f ../tplate/INCAR    $RUNDIR
endif

#cp -f POTCAR   $RUNDIR

if ( -e ../tplate/POTCAR ) then
  cp -f ../tplate/POTCAR   $RUNDIR
else if ( -e ../tplate/POTCAR.gz ) then
  zcat ../tplate/POTCAR.gz   >$RUNDIR/POTCAR
else if ( -e ../../POTCAR.gz ) then
  zcat ../../POTCAR.gz   >$RUNDIR/POTCAR
endif

#if ( \$?nested ) then
if ( "$nesting" != "" ) then
  echo $NERSC_HOST> nested_run
endif


cp -f POSCAR   $RUNDIR

cd $RUNDIR

\$VSPCMD $add $RUNDIR/"$AAA"-"$h".error

if ( ! -z CONTCAR ) then
      set nTHz = \`grep THz OUTCAR | wc -l\`
      if ( "\$nTHz" != "0" ) then
	cp -f CONTCAR $WORKDIR/.
	cp -f OSZICAR $WORKDIR/.
	cp -f OUTCAR $WORKDIR/.
	cp -f vasp*.xml $WORKDIR/.
      endif
endif

cd $WORKDIR

if ( -e OUTCAR ) gzip -f OUTCAR

if ( -e nested_run ) then
  rm nested_run
endif

vaspnesting:

if ( \$?lockedbyme ) then
  rm LOCKED
endif

end_end

        chmod u+x "$AAA"-"$h"

if ( "$nesting" != "" ) then
  if ( -e $nestfile ) then
      set bfile = `cat $nestfile | sed "s/cd //g;s/; /\//g"`
      echo "cd `pwd`; "$AAA"-$h" >> $bfile
  endif
  echo "cd `pwd`; "$AAA"-$h" > $nestfile
endif

echo "cd `pwd`; "$AAA"-$h"
        cd ..
        endif
        endif
end

