#!/bin/tcsh
#
set lthr = 5000
set ethr = 10000

set nk = 0
if ( -e StaticConvergent ) then
  set nk = `cat StaticConvergent | awk  '{print $2}'`
  if ( "$nk" > 3000 ) then
    set StaticDone
    goto getout0
  endif
endif

set outcar = OUTCAR.gz
if ( -e OUTCAR ) then
  if ( ! -z OUTCAR ) then
    set outcar = OUTCAR
  endif
endif
if ( ! -e $outcar ) goto checkrelax
if ( -z $outcar ) goto checkrelax

set zipped = `file $outcar | grep "gzip compressed data"`

if ( "$zipped" != "" ) then
  set enmax = `zcat $outcar | grep ENMAX | tr -d ';' | sort -k3 -n | tail -1 | awk '{print $3}' | sort -n | tail -1`
  set encut = `zcat $outcar | grep ENCUT | tr -d ';' | awk '{print $3}' | sort -n | tail -1`
  set ismear = `zcat $outcar | grep SMEAR | tr -d ';' | awk '{print $3}' | sort -n | tail -1`
else
  set enmax = `grep ENMAX $outcar | tr -d ';' | sort -k3 -n | tail -1 | awk '{print $3}' | sort -n | tail -1`
  set encut = `grep ENCUT $outcar | tr -d ';' | awk '{print $3}' | sort -n | tail -1`
  set ismear = `grep SMEAR $outcar | tr -d ';' | awk '{print $3}' | sort -n | tail -1`
endif

set pwdc = `pwd`
set tmpdir =  $SCRATCH/`echo $pwdc | sed "s|/|_|g;s|_global_project_projectdirs_m891_yiwang62|prj|g"`
set ibzkpt =  $tmpdir/IBZKPT

if ( -e $ibzkpt ) then
if ( ! -z $ibzkpt ) then
  set line = `grep "Tetrahedra" $ibzkpt -n | tail -1`
  if ( "$line" != "" ) then
    set n1 = `echo $line | sed 's/:/ /g' | awk '{print $1}'`
    set nk = `head -$n1 $ibzkpt | awk '{print $4}' | awk '{total += $0} END{print total}'`
  else
    set nk = `awk '{print $4}' $ibzkpt | awk '{total += $0} END{print total}'`
  endif
  set natom = `head -7 $tmpdir/POSCAR | tail -1 | awk '{ nn=0; for (i=1; i<=NF; i++) nn += $i; print nn;}'`
  @ nk = "$nk" * "$natom"
endif
endif

if ( -e ../tplate/INCAR.Static ) then
  set en0 = `grep ENCUT ../tplate/INCAR.Static | sed "s/ENCUT//;s/=//"`
  set high = `ari -n -f %.0f $encut - $en0 / $enmax x 100 +25.01`
else
  set high = `ari -n -f %.0f $encut - $enmax / $enmax x 100`
endif

if ( ("$high" >= "25") && ("$ismear" == "-5") ) then
  if ( "$nk" > 3000 ) then
    set StaticDone
  endif
endif

checkrelax:

set ofi = "OSZICAR"
if ( -e $ofi ) then
  set line = `grep "E0=" -a $ofi -n | tail -1`
  if ( "$line" == "" ) goto getout11
  set ddE = `echo $line | awk '{print $9}' | sed "s/=//g"`
  set dE = `ari -n -f %.0f $ddE x  $lthr | tr -d '-'`

  set n1 = `echo $line | sed 's/:/ /g' | awk '{print $1}'`
  if ( "$dE" != 0 ) then
    set n3 = `grep "E0=" -a $ofi | wc -l`
    if ( "$n3" != 1 ) then
      echo "not convergent ionic step" >>Convergence
      goto getout11
    endif
    set n2 = `wc -l <$ofi`
    if ( "$n1" != "$n2" ) then
      echo "not convergent ionic step" >>Convergence
      goto getout11
    endif
  else
    echo "convergent ionic step" >>Convergence
    echo "RelaxConvergent $nk $NERSC_HOST" > RelaxConvergent
  endif

  @ n1 = "$n1" - 1
  set line1 = "`head -$n1 $ofi | tail -1`"
  set ddE = `echo $line1 | awk '{print $4}' | sed 's/^-//g' | sed 's/E-/-/g' | sed 's/-/E-/g'`
  set dE = `ari -n -f %.0f $ddE x  $ethr | tr -d '-'`
  if ( "$dE" != 0 ) then
    echo "not convergent electronic step" >>Convergence
    goto getout11
  else
    echo "convergent electronic step" >>Convergence
    echo "RelaxConvergent $nk $NERSC_HOST" > RelaxConvergent
    if ( "$nk" < 500 ) then
      goto getout11
    else
      goto getout0
    endif
  endif
else
  goto getout1
endif

getout0:
if ( ! $?StaticDone ) then
  goto getout10
else
  set n3 = `grep "E0=" -a OSZICAR | wc -l`
  if ( "$n3" != 1 ) goto getout10
  set n4 = `grep "E0=" OSZICAR | tail -1 | awk '{print $4}'`
  if ( "$n4" != "E0=" ) then
    rm OSZICAR
    goto getout10
  endif
  if ( $?nk ) then
    echo "StaticConvergent $nk $NERSC_HOST" > StaticConvergent
  else
    echo "StaticConvergent 4000 $NERSC_HOST" > StaticConvergent
  endif
endif
echo "0"
exit

getout10:
echo "10"
exit

getout1:
echo "1"
exit

getout11:
echo "11"
exit
