#!/bin/tcsh
#

set OFILE = "OSZICAR"
set CFILE = "CONTCAR"
set www = `pwd`

unalias rm
unalias cp
unalias mv
set s = "`pwd`"
set h = $s:t
set nnode = 32
set mem = 60000
set neb = 1
set ppn = 32
set knl = ""
set walltime = "24:00"
if ( "$NERSC_HOST" == "edison" ) then
  set nnode = 24
  set ppn = 24
  set walltime = "36:00"
endif

set add = '&'
set pbsop = ""
set njob = 16
set nvol = 4
set kpar = ""
set prec = ""
set incar = ""
set scale = ""
set rerun = ""
set imix = ""
set imixm = ""
set gamma = ""
set nesting = ""
set aaaa = ""
set ibrion = ""
set lreal = ""
set remove_repeat = ""

foreach option ( $* )
  if (x$1 == "x-node") then
    shift
    set nnode="$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nesting") then
    set nesting = "-nesting"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-remove_repeat") then
    set remove_repeat = "-remove_repeat"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-LREAL") then
    set lreal = "-LREAL"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-AAAA") then
    shift
    set aaaa = "-AAAA $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-IBRION") then
    shift
    set ibrion = "-IBRION $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-kpar") then
    shift
    set kpar = "-kpar $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-prec") then
    shift
    set prec = "-prec $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-INCAR") then
    shift
    set incar = "-INCAR $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-Gamma") then
    set gamma = "-Gamma -N_kpoint 1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-dir") then
    shift
    set phases = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-mem") then
    shift
    set mem = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-njob") then
    shift
    set njob = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-nvol") then
    shift
    set nvol = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-W") then
    shift
    set walltime = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-scale") then
    shift
    set scale = "-ethr $1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-ppn") then
    shift
    set ppn = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-knl") then
    set knl = "-knl"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-IMIX") then
    shift
    set imix = "-IMIX $www/$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-IMIXM") then
    shift
    set imixm = "-IMIXM"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-rerun") then
    set rerun = "-rerun"
    if ( "$#argv" != 0 ) shift
    continue
  else
    set pbsop = "$pbsop $1"
    if ( "$#argv" != 0 ) shift
  endif
end

set nestfile = "$s/nestfile"
if ( -e $nestfile ) then
  rm $nestfile
endif

set file = "$s/jobfile"
echo -n >$file

foreach dir ( $phases )
#foreach dir ( V*/PBEsol/ )
#foreach dir ( tI6*/PBEsol/ )
  cd $www
  if ( ! -e $dir/tplate ) continue
  if ( -e $dir/good22.dat ) then
    set nl = `wc -l <$dir/good22.dat`
    if ( "$nl" >= 7 ) continue
  endif

  cd $dir
    if ( "$remove_repeat" != "" ) then
      set ddd = `pwd`
      set ecl = "`grep "$ddd" ~/bin/hbin/eclIN718.dat`"
      if ( "$ecl" != "" ) then
        echo "$ddd skipped for possible repeated strucrue"
        continue
      endif
    endif
    echo `pwd` `date`

    set nl = 0
    if ( -e frun22.dat ) set nl = `wc -l frun22.dat | awk '{print $1}'`
    #set rec0 = `grep "foreach ee (" crun | tail -1 | awk '{print $4}'`
    #set rec1 = `grep "foreach ee (" crun | tail -1 | awk '{print $5}'`
    #set lc = `ari -n -f %6.3f  $rec1 - $rec0`

    if ( "$nl" > 1 ) then
      set rec1 = `grep "foreach ee (" crun | tail -1 | awk '{print $5,"-",$4}'`
      set lc = `ari -n -f %6.3f  $rec1`
      set x = `sort -k2,2g  frun22.dat | head -1 | awk '{print $3}'`
      set nb = -2
      set llist = ""
      set flist = ""
      while ( "$nb" <= 4 )
        set lx = `ari -n -f %9.3f $lc x $nb + $x`
        set flist = "$flist $lx"
        set of = "V$lx/POSCAR"
        if ( ! -e $of ) then
          set llist = "$llist $lx"
        else if ( -z $of ) then
          set llist = "$llist $lx"
        endif
        @ nb = "$nb" + 1
      end
    else if ( -e crun ) then
      set flist = `grep "foreach ee" crun | sed "s/foreach ee (/ /g;s/)//g"`
      set llist = "$flist"
    endif

      set olist = `grep "foreach ee" ecmd | sed "s/foreach ee (/ /g;s/)//g"`
      set xRUN = "foreach ee ($flist )"
      if ( "$flist" != "$olist" ) then
        sed "s/ARUN/$xRUN/g" <~/bin/hbin/vaspecmd >ecmd
        chmod u+x ecmd
        sed "s/ARUN/foreach ee ($llist )/g" <~/bin/hbin/vaspmcmdf >mcmdf
        chmod u+x mcmdf
	mcmdf -Relax
      endif

      sed "s/ARUN/$xRUN/g" <~/bin/hbin/vasparun >frun
      chmod u+x frun
      frun $lreal $ibrion $aaaa $nesting -nestfile $nestfile $pbsop $imixm $gamma $incar $imix $kpar $prec $scale $rerun -node $nnode -ppn $ppn -mem $mem "$knl" >>$file
end
