#!/bin/tcsh
#
unalias rm
unalias cp
unalias mv
set s = "`pwd`"
set h = $s:t
set nnode = 32
set mem = 60000
set neb = 1
set ppn = 32
set knl = ""
set walltime = "24:00"
set queue = "regular"
set ylock = "jwork"

if ( "$NERSC_HOST" == "edison" ) then
  set nnode = 24
  set ppn = 24
  set walltime = "36:00"
endif

set add = '&'
set pbsop = ""
set njob = 16
#set hj = "MJOB"
set hj = "$h"
foreach option ( $* )
  if (x$1 == "x-node") then
    shift
    set nnode="$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-ylock") then
    set ylock="ylock"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-ywlock") then
    set ylock="ywlock"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-wlock") then
    set ylock="wlock"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-Q") then
    shift
    set queue="$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-dir") then
    shift
    set dir = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-mem") then
    shift
    set mem = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-hj") then
    shift
    set hj = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-njob") then
    shift
    set njob = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-njob") then
    shift
    set njob = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-ppn") then
    shift
    set ppn = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-W") then
    shift
    set walltime = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-knl") then
    set knl = "-knl"
    if ( "$#argv" != 0 ) shift
    continue
  else
    if ( "$#argv" != 0 ) shift
  endif
end

@ tnode = "$nnode"

set i = 0
while ( 1 == 1 )
  set hjdir = "j-$hj$i"
  @ i = "$i" + 1
  if ( -e $hjdir ) continue
  mkdir "$hjdir"
  break
end

cd $hjdir
cp ../jobfile .
set file = "`pwd`/jobfile"
set nl = `wc -l <$file`
if ( "$njob" > "$nl" ) set njob = "$nl"
set jobdir = `pwd`

set JOB = "JOB"
vasppbsN -node $tnode -ppn $ppn $knl -W $walltime -mem $mem -Q $queue | grep -v VSPCMD | grep -v tmpdir >$JOB

cat <<end_end >>$JOB

sleep second

while ( 1 == 1 )
  cd $jobdir
  set cmd = "\`$ylock $jobdir/jobfile\`"
  if ( "\$cmd" == "alljobdone" ) then
    exit
  else
    echo \$cmd
    set cmd0 = \`echo \$cmd | awk '{print \$1,\$2}' | sed "s/;//"\`
    set cmd1 = \`echo \$cmd | awk '{print \$3}'\`
    \$cmd0
    \$cmd1
  endif
end
end_end

set kk = 0
while ( "$kk" < "$njob" )
  set sss = "`ari -n -f %.3f 0.01 x $kk`s"
  set J = $hjdir-$kk
  sed "s/second/$sss/" <$JOB >$J
  sbatch $J
  @ kk = "$kk" + 1
end
cd ..
