#!/bin/tcsh

set PY = /global/project/projectdirs/m891/yiwang62/EV/bin/
set g0 = $PY:h
set gg = $g0:h
set srcdir = $gg/"Frame"
set N_kpoint=10
set K_TYPE="G"

foreach o ( $* )
  if (x$1 == "x-N_kpoint") then
    shift
    set N_kpoint = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else if (x$1 == "x-K_TYPE") then
    shift
    set K_TYPE = "$1"
    if ( "$#argv" != 0 ) shift
    continue
  else
    if ( "$#argv" != 0 ) shift
  endif
end

set line = `head -7 ../tplate/POSCAR | tail -1`
set natom = `echo $line | awk '{ nn=0; for (i=1; i<=NF; i++) nn += $i; print nn;}'`

set Nk = `python -c "print (($N_kpoint ** 3 / $natom) ** .33333333333)"`

if ( ! -e POSCAR ) then
  cp CONTCAR POSCAR
endif

set K_LENGTH=`$PY/kvecl $Nk <POSCAR`

sed "s|K_LENGTH|$K_LENGTH|g;s|K_TYPE|$K_TYPE|g" < $srcdir/frame/tplate/KPOINTS >KPOINTS.$N_kpoint
